/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thistestuser_cursorhelper_MainScreen */

#ifndef _Included_com_thistestuser_cursorhelper_MainScreen
#define _Included_com_thistestuser_cursorhelper_MainScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thistestuser_cursorhelper_MainScreen
 * Method:    setMouseLocation
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thistestuser_cursorhelper_MainScreen_setMouseLocation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_thistestuser_cursorhelper_MainScreen
 * Method:    getMouseLocation
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_thistestuser_cursorhelper_MainScreen_getMouseLocation
  (JNIEnv *, jclass);

/*
 * Class:     com_thistestuser_cursorhelper_MainScreen
 * Method:    setupDPI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thistestuser_cursorhelper_MainScreen_setupDPI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
